### PR TITLE
Adding PowerFactory implementation of distributed solar PVD1

### PR DESCRIPTION
**Pull request by tinrabuzin**
This should probably be merged after #266.

### CODE REVIEW

**Review by dietmarw — CHANGES_REQUESTED** [review]
I have now rebased this extension onto master (with the now merged #266). However, this extension has still a number of issues:
 - structural problems in `StaVmeas` due to conditional inputs not implemented correctly
 - missing description strings in all the models
 - missing documentation of the models
 - untidy diagrams
@tinrabuzin could you have a look otherwise we have to postpone this merge to the future.

**Comment by dietmarw** [comment]
BTW, I had to squash and rebase, so when working on this do a hard reset of your checkout branch.

**Comment by tinrabuzin** [comment]
>       @tinrabuzin could you have a look otherwise we have to postpone this merge to the future.

I don't have any time right now to fix this, sorry. Eventually, I will look into it.

**Comment by dietmarw** [comment]
@tinrabuzin That is fine. Since this are additional models there is no rush. So I'm gonna reassign the milestone again for the next release.

**Comment by dietmarw** [comment]
This PR is now rebased onto the latest v3.1.0-dev master

**Review by dietmarw — APPROVED** [review]
This is now good to go. 
The test still fails due to:
```
Cannot differentiate discrete variable:
elmVac.v
```
but since this is really an issue of the `OpenIPSL.Electrical.Solar.PowerFactory.General.ElmVac` model which was not touched by this PR I leave that to be figured out at a later stage. 
I'm curious when this will be discovered/reported the first time ;-)

**Pull request merged**
