### PR TITLE
Prefer Text.textColor attribute (and do no longer use deprecated Text.lineColor)

### PR DESCRIPTION
**Pull request by tbeu**
Additionally, I enabled the appropriate CI check.

### CODE REVIEW

**Review by dietmarw — CHANGES_REQUESTED** [review]
I'm not sure we should adopt this just yet since I seem to remember that some tools still write the `lineColor` annotation out which then means failed checks. So I rather hold off on this one.

**Comment by tbeu** [comment]
If a tool claims MSL 4.0.0 support it also supports Test.textColor, hopefully.

**Comment by dietmarw** [comment]
But you can use older tools also with MSL 4.0.0 :-P just fine. Also, there is no such thing as MSL[version] support but Modelica-specification support. You of all people should know that :-P

**Comment by dietmarw** [comment]
See also: https://github.com/OpenModelica/OpenModelica/issues/9498

**Comment by dietmarw** [comment]
@marcelofcastro Here the reasons why it should not be merged:
1. All tools at least back to the time of Dymola 2020 support `textColor` when reading the models. So one does not notice this issue when working with the library from a user's perspective.
2. The issue is that if developers work with a tool that does not write out `textColor` but the old `lineColor` when working with models will cause immediately the CI to fail when wanting to contribute. 
3. I **really** don't want to get forced to use any ribbon-based tool just because of this minor issue.

**Comment by marcelofcastro** [comment]
Okay, makes sense. But should we track that using an issue?

**Comment by dietmarw** [comment]
> Okay, makes sense. But should we track that using an issue?

Good idea. Done so in #314 and will close this now.

**Pull request closed without merging**
