### PR TITLE
Fixing PSAT Machines, AVR I & II, and making everything compile.

### PR DESCRIPTION
**Pull request by janlav**
There were some errors in the PSAT AVRs Type I and II and their respective tests in the Examples folder which is fixed in this commit.

### CODE REVIEW

**Comment by janlav** [comment]
Don't merge this until #144 is taken care of

**Comment by janlav** [comment]
@dietmarw thank you for your comments, I will make sure to do that!

**Comment by MaximeBaudette** [comment]
@dietmarw I don't want to just "dismiss" your review, but I can't validate the changes instead of you.

**Comment by sjoelund** [comment]
This PR seems to have broken 4 models simulating in OpenModelica ([log](https://libraries.openmodelica.org/branches/history/v1.12/2017-10-12%2023:32:54..2017-10-14%2000:04:00.html)):
```
OpenIPSL.Examples.Machines.PSAT.Order3test2
OpenIPSL.Examples.Machines.PSAT.Order3test2_TG
OpenIPSL.Examples.Machines.PSAT.Order3test2_perturbation
OpenIPSL.Examples.Machines.PSAT.Order4test2_AVR
```

**Comment by janlav** [comment]
@sjoelund I am looking into this, it seems like there is still some problem with the handling of the different per-unit systems, should be fixed within a day or so.

**Comment by MaximeBaudette** [comment]
@sjoelund 
Not sure if this PR broke those tests, or if it is because we have started to populate more of our examples with individual experiments annotations as you requested. In such case it can be an old error that we discover only now ;-)

**Comment by sjoelund** [comment]
The log says that at c339aa8, these models simulated using OpenModelica :)

**Comment by MaximeBaudette** [comment]
@sjoelund Are you pulling our master automatically? 
BTW, I saw you were generating svg graphs for the exec time of the testing suite for each library. Would you consider generating a badge that could easily be integrated in the repository readme like Travis: 
[Build Status](https://travis-ci.org/OpenIPSL/OpenIPSL)

**Comment by sjoelund** [comment]
The script I use is a bit specialized. It will download libraries and update the OpenModelica branches to the latest versions and test all our branches to all libraries. It takes a few weeks for a full run, so results are cached. When a run finishes, the script looks at what changed since the previous run; if it did I email the OpenModelica developers who made commits since the last run. I could possibly setup email notifications for when a library changes as well although commit hashes and GitHub URL aren't really stored so it would be email to a fixed contact.

Making a pass/fail badge doesn't make that much sense because the script has no real sense of what a good result is, but I suppose it might be possible to create something just listing xx/yy examples simulating.

**Pull request merged**
