### PR TITLE
Pass the build test with the library 

### PR DESCRIPTION
**Pull request by MaximeBaudette**
The aim with this branch is to solve all Model check issues that we have in the Library
The goal is to close the following issues:
#7
#13
#22

and #16 

The PR should not be merged in it's current state and I invite people to contribute in this branch _ModelCheck_Fix_ to solve all the issues. 
N.B: Do not forget to mention which issue you are working on.

### CODE REVIEW

**Comment by lvanfretti** [comment]
Does this need to be reviewed also? @MaximeBaudette

**Comment by MaximeBaudette** [comment]
@lvanfretti 
No, I just keep this one open until all the issues have been fixed ;-)

**Comment by dietmarw** [comment]
Is there still a point in having this PR. Or is it superseded and can be closed unmerged?

**Comment by dietmarw** [comment]
All the issues mentioned in this PR were fixed a long time ago making this PR superfluous.

**Pull request closed without merging**
