### PR TITLE
Adding examples from OpenIPSL used by RaPID

### PR DESCRIPTION
**Pull request by lvanfretti**

### CODE REVIEW

**Comment by lvanfretti** [comment]
@maximebaudette can you please do this review?

**Comment by tinrabuzin** [comment]
@MaximeBaudette @lvanfretti I think those are outdated models of line and gen aggregation. I updated them in the RaPiD repo a while ago. I think so at least.

**Comment by lvanfretti** [comment]
I'll update them.
Do you have PSS/E files or PSAT files for them?
Also for MOSTAR!?

@maximebaudette please dump this commit then.

---
Sent from a mobile device.

Luigi Vanfretti, +46 73-461 24 78‬
https://www.kth.se/profile/luigiv/

**Comment by MaximeBaudette** [comment]
@lvanfretti You can continue committing into this branch and replace the files in question. It's fine.

**Comment by lvanfretti** [comment]
Ok Maxime, 😜
As you know, I'm GIT illiterate so you are forced to explain the obvious!

---
Sent from a mobile device.

Luigi Vanfretti, +46 73-461 24 78‬
https://www.kth.se/profile/luigiv/

**Pull request merged**
