### PR TITLE
Fixes #172 by removing duplicate implementations (with conversion)

### LINKED ISSUE #172: PSAT transformer package
I noticed that there are 2 transformer models implementing the fixed tap ratio model from PSAT. For the look of it, these models are identical. 
Look into removing the duplicate model, and clean up package. 

See #164  to prepare a script updating the model to change to the correct model

### PR DESCRIPTION
**Pull request by dietmarw**
This removes the duplicate transformer models and provides a conversion script. The script was tested on ApplicationExamples/IEEE14 which uses the changed models.

### CODE REVIEW

**Comment by dietmarw** [comment]
This should be applied after PR #177 is merged.

**Comment by dietmarw** [comment]
@marcelofcastro The CI will currently fail because we are testing the ApplicationExamples. One of them (also used for the conversion tests) will fail.
Maybe @sjoelund can tell if OMC supports conversion scripts so that one could test an application library that uses OpenIPSL but needs converting.

**Comment by sjoelund** [comment]
OMC will not perform conversions.

**Comment by marcelofcastro** [comment]
@dietmarw I just realized that, since we are going to update to a 2.0 version, we will need to update luigi's email in every annotation (and even add my email and/or yours). Maybe we can use something similar to the conversion script to do such thing.

**Comment by dietmarw** [comment]
> @dietmarw I just realized that, since we are going to update to a 2.0 version, we will need to update luigi's email in every annotation (and even add my email and/or yours). Maybe we can use something similar to the conversion script to do such thing.

I'm afraid this has to be done manually. Of course it can be automated with things like `sed`. For now I've only updated the contact when I touched a model (and felt like it ;-) ). But I think this should actually be unified. See #179

**Pull request merged**
