### PR TITLE
Add Soft PMU model

### PR DESCRIPTION
**Pull request by MaximeBaudette**

### CODE REVIEW

**Comment by lvanfretti** [comment]
@janlav will you do the review? You can make changes to the commit later when you have time.

**Comment by MaximeBaudette** [comment]
@janlav I think there was a misunderstanding here with @lvanfretti, weren't you supposed to fix something before merging ?

**Comment by janlav** [comment]
@MaximeBaudette I didn't read it that way; I think this is an initial commit (I verified that it is runnable model) and that improvements can be made with later commits. Let me know if I am wrong @lvanfretti.

**Comment by lvanfretti** [comment]
@janlav you read it the right way. You can add stuff when you have the chance, better to have the basic stuff in now that works, improvements are always welcome latter.
Ok @MaximeBaudette ?

**Comment by MaximeBaudette** [comment]
Ok

**Pull request merged**
