### PR TITLE
Add MonoTri Library

### PR DESCRIPTION
**Pull request by MaximeBaudette**
I'm opening this PR to prepare for merging the MonoTri package.

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
DO NOT MERGE FOR NOW

**Comment by MaximeBaudette** [comment]
ok @janlav @marcelofcastro please check that everything is in order, I think it is ready to merge now.
It was a bit of problematic with Travis until I discovered that one of the models had a mistake it its name (file with a capital letter when the modelica model didn't have one, OM is super sensitive to this)

**Comment by dietmarw** [comment]
@MaximeBaudette 
> OM is super sensitive to this
Not OM itself but the Modelica Spec and any *proper* operating system is case sensitive ;-)

**Comment by MaximeBaudette** [comment]
@dietmarw 
Tell that to my machine, where Dymola and git didn't detect the file rename issue.

**Comment by dietmarw** [comment]
It's not the tools but your operating system.

**Comment by MaximeBaudette** [comment]
I know ;-) 
And FYI I didn't choose my OS, it was forced upon me.

**Pull request merged**
