### PR TITLE
Convert internal variable to connector

### LINKED ISSUE #317: Connect on non-connectors
In `OpenIPSL.Electrical.Solar.PowerFactory.General.ElmGenstat` there is:

```
    connect(sinref, sinu);
    connect(cosref, cosu);
```

But neither `sinu` nor `cosu` are connectors.

System Modeler reports this when validating `OpenIPSL.Tests.Solar.PowerFactory.DIgSILENT_PV`:

> Error: OpenIPSL.Electrical.Solar.PowerFactory.General.ElmGenstat [21:5-21:5] Invalid connect equation. cosu is not a connector.
>    Component references in connect equations must be of the form c_1.c_2...c_n or m.c_0 where c_i is an instance of a connector class for all values of i.

> Error: OpenIPSL.Electrical.Solar.PowerFactory.General.ElmGenstat [20:5-20:5] Invalid connect equation. sinu is not a connector.
>    Component references in connect equations must be of the form c_1.c_2...c_n or m.c_0 where c_i is an instance of a connector class for all values of i.

### PR DESCRIPTION
**Pull request by dietmarw**
Fixes #317 by using protected connectors instead of helping variables.

### CODE REVIEW

**Comment by marcelofcastro** [comment]
That's a nice fix @dietmarw. Should we also update the integrator initialization value that is giving you the division by zero?

**Comment by dietmarw** [comment]
@marcelofcastro Can you remind me again what the issue is?

**Comment by marcelofcastro** [comment]
You [mentioned it](https://github.com/OpenIPSL/OpenIPSL/issues/317#issuecomment-1303527227) in a comment on issue #317. Hopefully the link will work

**Comment by dietmarw** [comment]
@marcelofcastro Fixed. Have another look.

**Review by marcelofcastro — APPROVED** [review]
Just tested and it works fine. The PR is approved.

**Pull request merged**
