### PR TITLE
Adjusted Machine Base Power Rating in the Infinite Bus to 100 MVA

### PR DESCRIPTION
**Pull request by ManuelNvro**
Adjusted the Machine Base Power Rating in the Infinite Bus to 100 MVA of all of the PSSE Examples in the library

### CODE REVIEW

**Comment by marcelofcastro** [comment]
@ManuelNvro Since you're modifying the extended partial model, maybe it's better just to change the Partial...

**Comment by dietmarw** [comment]
@marcelofcastro That would be a bad Idea. Changing the default explicitly for the PSSE models makes sense since PSSE normally uses 100MVA as base. Changing it in the base model would mean that ALL models that uses that base model (which is not only PSSE) will have their defaults change. And that means that user models suddenly get a different base. So you should be extremely careful here.

**Comment by marcelofcastro** [comment]
@dietmarw he changed the machine base of the infinite bus to 100 MVA because in the original models they were 100 MVA (in OpenIPSL version 1.5 for example). Since you did the unit modification, the base became 0.0001 (100 in the old version becomes 0.0001 MVA in the new unit format). That's why I think we should replace the value in the SMIB partial...

**Comment by dietmarw** [comment]
OK I see. In that case none of the example models from master branch were converted yet in order to have them as test models for the automatic conversion. Unfortunately I did not have time to continue on the conversion yet. So setting it to 100e6 in GENCLS should be fine as there currently is no other default value defined. **But** it should better be done as a start value so that the tool can warn the user about not having set explicit values and default being used. 

@ManuelNvro I was wondering about the annotations. I see that the examples are not looking nice as they are so did you do some graphical clean up at the same time?

**Comment by ManuelNvro** [comment]
@dietmarw No, I just forked from the OpenIPSL repository and changed the bases, the graphics were not touched.

**Comment by dietmarw** [comment]
OK in that case the PR needs to be changed to only fix the start value of machine base to 100e6 in one place. Can you do that?

**Comment by ManuelNvro** [comment]
@dietmarw  yes, I had to create a new pull request. Disregard this one.

**Pull request closed without merging**
