### PR TITLE
(doc) Small update in publication list

### PR DESCRIPTION
**Pull request by MaximeBaudette**

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
@lvanfretti here also

**Comment by lvanfretti** [comment]
@MaximeBaudette please do the changes mentioned by @dietmarw

**Comment by MaximeBaudette** [comment]
looking into it now

**Comment by MaximeBaudette** [comment]
Now it should be fine @dietmarw

**Comment by lvanfretti** [comment]
@dietmarw maxime has fixed the pull and I am "dismisse review" and merging

**Pull request merged**
