### PR TITLE
Introduce SI Units in ThreePhase package

### PR DESCRIPTION
**Pull request by MaximeBaudette**

### CODE REVIEW

**Comment by marcelofcastro** [comment]
Maxime, I realized that you replaced the `/(Sn/3)` by `/Sn` in some models. Are you sure that this is the correct implementation? I think that division by 3 was necessary to get the correct results for each phase in a three-phase system.

**Comment by MaximeBaudette** [comment]
Yes, I saw that in your models, but I think it's incorrect, cause it will multiply the load by 3.

**Comment by marcelofcastro** [comment]
@MaximeBaudette But the problem is that you are using three-phase power to represent quantities for each phase. I am almost sure that diving single-phase power by three-phase power base will give us wrong results. I will check if the 4-bus example gives the same results as before.

**Comment by marcelofcastro** [comment]
@MaximeBaudette As I suspected, dividing the single-phase power by `Sn` is incorrect. The quantity `Sn` is a three-phase power base. However, on the calculations in per unit for single phase quantities, we need the single-phase power base which is `Sn/3`. So you are going to correct that.                        
                                                                                                                                                                       In addition, the examples do not simulate because instead of `ThreePhase.Buses.Bus_3Ph` you are using `ExtremumSeekingBis.Examples.OpenIPSL_Example.Components.Meas_3Ph`. By the way, I don't understand why the check by travis haven't completed yet.

**Comment by MaximeBaudette** [comment]
HI Marcelo, 

Let me have another look at it to try to understand what you actually did. in you per-unit implementation of the 3 phase component. 
Do you want a Sn/3 base per phase? In this case I need to look up where you do the change of base in your models. 
I'll get back in touch.

**Comment by marcelofcastro** [comment]
Hi @MaximeBaudette ,  

Yeah, the calculations of phase voltages and phase currents are done by using the singe-phase power base (Sn/3). That's why I used this base per phase. 

Cool, let me know if you need anything.

**Comment by marcelofcastro** [comment]
@MaximeBaudette why is this still saying that some checks were not successful if we can see that the build was in fact successful? 

Screenshot from 2020-04-26 15-31-24

**Comment by MaximeBaudette** [comment]
@marcelofcastro 
I'm gonna close this PR, because in the end, everything is in #198

**Pull request closed without merging**
