### PR TITLE
Moves and converts Application Examples and old Examples to Examples and Tests, respectively

### LINKED ISSUE #246: Moving Application Examples
We need to move application examples inside the library and set examples to be called Unit Tests.

### PR DESCRIPTION
**Pull request by marcelofcastro**
(fixes  #246)
This PR is supposed to add the ApplicationExamples into the main library body. Therefore it covers:

- Incorporation of ApplicationExampls into OpenIPSL as Examples;
- Changing old Examples into Tests subpackage;
- Documentation for example systems;
- Fixing small issue with Limited Lag component (plus because it was a very simple fix).

### CODE REVIEW

**Comment by marcelofcastro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by dietmarw — COMMENTED** [review]
I've done the following changes:
 - rebased on latest master
 - removed all trailing . from description strings (causes noise and looks ugly)
 - moved Tests to the last position
 - cleaned up all annotations with help of [ttws](https://github.com/simulatino/trimtrailingwhitespaces)
 - removed uses annotations
 - removed vendor annotation where possible
 - sorted the examples and tests alphabetically

Open questions:
  1. The Tutorial depends on `Modelica_LinearSystems2` which is a non-standard compliant Dymola specific library. So I rather not have it loaded by default. Should we keep the functions but not add M_LS2 to the uses annotation?
  2. There is a heavy use of `__Dymola_` annotations for the fixed step simulations. Is that necessary for the examples or would they also work just fine with DASSL?
  3. Similar I wonder if `__Dymola_experimentFlags(Advanced(Define(DAEsolver=true)))` is needed?

**Comment by marcelofcastro** [comment]
Maybe @lvanfretti can provide more information, but from my perspective:

1. I think that we can do as you say. Keep the functions but let us not add M_LS2. Maybe we can add one sentence explaining this.
2. In many of the cases, I just kept the fixed time step thing. However, I believe DASSL would work just fine, so I would remove all of these annotations but the one in the DAE_TestSystems example.
3. The DAE_TestSystems is an application example that shows how the DAE mode from Dymola can improve simulation time. I believe I have mentioned that in the model's documentations. Therefore, I believe we can maintain those annotations as I believe they will be just ignored for all other modelica-compliant tool solver. 

What do you think?

**Comment by lvanfretti** [comment]
@marcelofcastro  and @dietmarw 
1. Ok with me to remove `Modelica_LinearSystems2` (MLS2), but, perhaps we can put something in the documentation indicating that the models of the tutorial are mostly designed to be used with MLS2 under Dymola. I know that a lot of this can be done with other tools, but it is much more convenient for a tutorial to do it directly in Dymola, so going forward, I hope to elaborate this tutorial further and it will rely anyway on Dymola.
2. There are several examples that will not work properly with DASSL. If I recall correctly, the ones related to exciters have some small time constants that will make the system "critically stable" which might or might not work using DASSL depending on the default tolerance. I think that we should do the following: (1) put in the documentation of the model the annotation so that we know how it should work in Dymola for future reference, (2) add in the diagram the note "see the annotations in the text layer for setting up experiment/simulation" or something similar, and perhaps (3) set up the annotation to use OpenModelica with similar settings. Then you can leave the experiment annotation plain vanilla, while being able to know how the example is tested. Perhaps we can use a particular annotation depending on the tool use, but that might be too much work...
3. I think you can make a note on the diagram layer similar to what I mentioned above in 2.(2). And yes, you should keep the annotations in this case anyway, perhaps we need to add the ones for OM also and put the info in the documentation.

Those are my suggestions. Let me know what you guys think.

**Comment by dietmarw** [comment]
1. OK then the PR can stay as it is
2. Since the vendor annotations don't do any harm (are just nice to get rid of if possible) we can leave them. You can decide if you want to add some additional documentation as to what the criterias are for the solver settings for the different examples if you want. But please do that in the info layer, not the diagram layer.
3. In that case no need to do anything.

**Comment by marcelofcastro** [comment]
2. I will test the examples to see if they really need Rkfix2. My experience tells me they might not need it anymore.

**Comment by lvanfretti** [comment]
@marcelofcastro that's good news!

**Review by dietmarw — APPROVED** [review]
Looks good to me now. Nice effort.

**Pull request merged**
